# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c09e4336ca19cdfb086b03262d247f0b1a3a1c63d83024f70ebe6465330a4ce7911afa711e43c8f7b8cd1bd917088ff6e527dfd5d627e5d914017f178d39a5c

test:
  secret_key_base: ff6d02aca7a01bf48e035aa574e854de47af7538cedf259d23471e547aa1f21b14bd2015ab312a829b99fcb173c2b3313be59f874dac191d5261a37bccaafeb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
